### ISSUE TITLE
Incomplete process polyfill causes exception

### ISSUE THREAD

**Issue by copy** [chenglou/require-polyfill#4]
Currently `process` is polyfilled like this:

```js
var process = {env: {}}
```

This causes a problem with `caml_sys_get_argv`, which assumes that if `process` exists, it has an `argv` property.

```js
function caml_sys_get_argv() {
  var match = typeof (process) === "undefined" ? undefined : (process);
  if (match !== undefined) {
    return /* tuple */[
            match.argv[0], // XXX: Cannot read property '0' of undefined
            match.argv
          ];
  } else {
    return /* tuple */[
            "",
            /* array */[""]
          ];
  }
}
```

**Comment by chenglou** [comment]
I've put process here as a hack because some packages accessed `process.env` and then post-processed them away in webpack. I think this can simply be removed. cc @IwanKaramazow for validations.

@bsansouci

**Comment by bsansouci** [comment]
I renamed to __process to avoid the collision with BS

**Comment by IwanKaramazow** [comment]
Fixed in https://github.com/chenglou/require-polyfill/commit/c310d2a3464b85eb02bdd458b8ba11f0d7a7508f (polyfilled with an empty array for now).

Feel free to re-open if anyone encounters any issues, works fine for me with an empty array
